/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lKNM0WoRqFE
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

"use client"; // Add this at the top of the file

import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from "@/components/ui/dropdown-menu";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardContent, CardTitle } from "@/components/ui/card";
import React, { useState } from "react";
import Image from "next/image";

export function Component() {
  // State to manage the visibility of the mobile menu
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  // Function to toggle menu visibility
  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };
  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <header className="sticky top-0 z-40 border-b bg-background">
        <div className="flex h-16 items-center justify-between px-4 sm:px-6 md:px-8">
          {/* Mobile Menu Button */}
          <button
            onClick={toggleMenu}
            className="sm:hidden p-2 rounded-md hover:bg-primary-hover transition-colors"
          >
            {/* Icon for the mobile menu button */}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              className="w-6 h-6"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M3.75 6.75h16.5m-16.5 5.25h16.5m-16.5 5.25h16.5"
              />
            </svg>
          </button>
          {/* Logo Button*/}
          <div className="flex items-center gap-4 sm:w-48 w-24" >
          <svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="100%" height="100%" viewBox="0 0 572.000000 161.000000" preserveAspectRatio="xMidYMid meet">

<g transform="translate(0.000000,161.000000) scale(0.100000,-0.100000)" fill="#ffffff" stroke="none">
<path d="M5548 1343 l-48 -4 0 -175 0 -175 -46 36 c-58 44 -113 59 -183 51 -152 -18 -253 -145 -253 -316 0 -129 54 -231 151 -283 99 -54 216 -43 299 28 42 36 42 36 42 12 0 -51 8 -57 75 -57 l62 0 -1 278 c0 152 1 351 4 442 l5 165 -30 1 c-16 0 -51 -1 -77 -3z m-141 -403 c100 -60 123 -219 46 -311 -92 -109 -254 -61 -294 87 -43 153 122 301 248 224z"/>
<path d="M620 1314 c-8 -3 -51 -71 -94 -152 -43 -81 -164 -302 -269 -492 -105 -190 -206 -373 -225 -408 l-34 -63 112 3 113 3 159 295 c222 410 308 561 317 555 5 -2 14 -33 21 -67 7 -35 15 -67 18 -71 2 -5 22 24 44 65 22 40 48 84 58 97 17 24 17 28 -8 120 -13 53 -27 99 -31 102 -7 8 -160 18 -181 13z"/>
<path d="M908 1112 c-17 -20 -504 -858 -514 -884 -6 -16 2 -18 85 -18 83 0 92 2 105 22 8 13 123 214 255 448 l241 425 -33 6 c-92 18 -124 18 -139 1z"/>
<path d="M2020 1075 c-113 -32 -187 -97 -244 -215 -30 -63 -31 -70 -31 -195 0 -125 1 -133 31 -195 80 -168 243 -253 426 -222 40 7 97 24 126 37 l53 24 44 -21 c25 -12 46 -20 48 -17 1 2 1 91 -1 197 l-4 192 -80 0 -80 0 6 -67 c4 -38 9 -89 12 -114 l5 -46 -53 -23 c-79 -34 -183 -39 -242 -11 -53 26 -101 77 -130 140 -30 66 -29 188 2 256 45 97 124 154 215 155 65 0 111 -23 173 -87 l51 -53 47 50 47 50 -21 30 c-82 116 -257 175 -400 135z"/>
<path d="M2857 1080 c-43 -11 -109 -43 -150 -74 -52 -38 -116 -134 -138 -208 -32 -103 -24 -230 19 -322 37 -78 115 -162 184 -194 106 -52 239 -52 345 -1 71 34 149 117 185 196 43 94 50 219 19 321 -50 166 -189 279 -354 287 -40 3 -89 0 -110 -5z m164 -142 c51 -15 112 -68 146 -125 36 -61 44 -176 18 -254 -23 -68 -101 -149 -161 -167 -99 -29 -178 -10 -249 61 -61 61 -85 122 -85 212 0 90 24 151 85 212 70 70 151 90 246 61z"/>
<path d="M2930 885 c0 -19 -8 -28 -34 -39 -43 -18 -66 -51 -66 -95 0 -28 9 -43 45 -78 43 -41 45 -45 45 -99 l0 -57 -49 5 c-48 5 -48 5 -42 -21 6 -20 16 -28 49 -35 34 -8 42 -14 42 -33 0 -16 6 -23 20 -23 15 0 20 7 20 29 0 22 6 31 23 36 33 11 65 44 72 76 8 36 -14 78 -59 113 -34 25 -36 31 -36 82 0 60 14 69 59 38 26 -18 39 -11 43 26 3 21 -3 26 -44 37 -40 12 -48 18 -48 39 0 17 -5 24 -20 24 -15 0 -20 -7 -20 -25z m0 -130 c0 -46 -7 -54 -28 -33 -22 22 -8 78 20 78 4 0 8 -20 8 -45z m56 -170 c13 -20 14 -28 4 -40 -21 -25 -30 -17 -30 25 0 47 4 49 26 15z"/>
<path d="M3932 1076 c-84 -27 -135 -74 -182 -166 -33 -62 -40 -196 -15 -271 23 -68 89 -139 158 -170 42 -19 70 -23 142 -23 77 0 98 3 146 27 30 15 65 37 78 51 l22 24 -23 46 -24 46 -33 -25 c-82 -60 -206 -71 -275 -24 -36 24 -75 83 -64 94 3 4 80 13 170 21 203 19 236 27 249 62 21 55 -21 180 -80 240 -70 70 -179 97 -269 68z m136 -126 c38 -23 74 -77 70 -104 -4 -27 -43 -36 -173 -39 l-110 -2 3 30 c11 103 126 166 210 115z"/>
<path d="M4673 1070 c-17 -6 -57 -28 -89 -49 -63 -42 -74 -40 -74 13 0 24 -3 27 -22 23 -13 -3 -45 -9 -73 -13 -27 -3 -53 -8 -56 -10 -3 -2 0 -31 7 -66 9 -41 14 -141 14 -285 l0 -223 70 0 70 0 0 201 c0 119 4 208 10 220 16 28 110 79 148 79 39 0 86 -22 98 -47 5 -10 9 -115 10 -233 l1 -215 72 -3 73 -3 -4 248 c-3 229 -5 251 -24 288 -12 22 -35 48 -53 58 -36 22 -132 31 -178 17z"/>
<path d="M1143 963 c4 -58 7 -243 7 -409 l0 -303 258 -3 c292 -3 282 -6 282 76 l0 51 -197 0 -198 0 -3 348 -2 347 -77 0 -76 0 6 -107z"/>
<path d="M3433 853 c4 -108 7 -305 7 -437 l0 -241 101 -62 c92 -58 108 -64 214 -85 l114 -22 135 38 c74 21 141 46 149 55 8 9 29 42 48 74 l34 59 733 -4 733 -3 -3 49 -3 49 -743 -2 -744 -1 -46 -52 c-26 -28 -52 -58 -58 -66 -5 -7 -51 -22 -102 -33 l-92 -19 -70 46 c-39 25 -70 47 -70 49 0 2 15 -1 32 -6 43 -12 87 -11 163 2 51 9 64 15 78 38 23 40 7 51 -74 51 -60 0 -75 4 -129 36 l-61 37 -100 -5 -101 -5 4 328 4 329 -80 0 -79 0 6 -197z"/>
<path d="M872 661 l-62 -116 21 -105 c11 -58 27 -136 36 -173 l15 -69 93 4 c51 1 96 5 98 8 5 5 -127 558 -135 565 -2 1 -31 -50 -66 -114z"/>
</g>
</svg>
</div>
          {/* Desktop Menu */}
          <div className="hidden sm:flex items-center justify-center gap-4">
            {/* Menu Items */}

            <Button variant="outline">Loans</Button>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline">Community</Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    Discord
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    Blog
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    Forum
                  </Link>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline">Resources</Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    FAQs
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    Stats
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link href="#" className="hover:underline" prefetch={false}>
                    Documentation
                  </Link>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
          {/* <div></div>
            <div></div>
            <div></div> */}
          {/* Right-side button */}
          <div className="flex items-center gap-4">
            <Button className="w-32">
              <Link href="/dashboard">Dashboard</Link>
            </Button>
          </div>
        </div>

        {/* Mobile Menu (shown when isMenuOpen is true) */}
        {isMenuOpen && (
          <div className="sm:hidden bg-background p-2">
            {/* Menu Items for Mobile */}

            <Button className="transition-colors w-full my-2">Loans</Button>
            <Button className="transition-colors w-full">Community</Button>

            <Button className="hover:bg-primary-hover transition-colors w-full my-2">
              Resources
            </Button>
          </div>
        )}
      </header>
      <main className="flex-1">
        <section className=" py-12 px-3 sm:py-16 md:py-20">
          <div className="grid gap-8 md:grid-cols-2">
            <div className="space-y-4">
              <h1 className="text-3xl font-bold sm:text-4xl md:text-5xl">
                Decentralized Peer-to-Peer Lending
              </h1>
              <p className="text-muted-foreground">
                Borrow and lend Algorand assets with customizable terms, secured
                by smart contracts.
              </p>
              <div className="flex gap-4">
                <Button>Become a Lender</Button>
                <Button variant="outline">Become a Borrower</Button>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <Card>
                <CardHeader>
                  <CreditCardIcon className="h-8 w-8 text-primary" />
                </CardHeader>
                <CardContent>
                  <h3 className="mb-2 text-lg font-bold">Loan Requests</h3>
                  <p className="text-muted-foreground">
                    Browse and select from a variety of loan requests with
                    flexible terms.
                  </p>
                  <Button variant="outline" className="mt-4">
                    View Loan Requests
                  </Button>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <WalletIcon className="h-8 w-8 text-primary" />
                </CardHeader>
                <CardContent>
                  <h3 className="mb-2 text-lg font-bold">Lender Dashboard</h3>
                  <p className="text-muted-foreground">
                    Manage your lending portfolio and monitor loan performance.
                  </p>
                  <Button variant="outline" className="mt-4">
                    View Dashboard
                  </Button>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <ContactIcon className="h-8 w-8 text-primary" />
                </CardHeader>
                <CardContent>
                  <h3 className="mb-2 text-lg font-bold">Smart Contracts</h3>
                  <p className="text-muted-foreground">
                    Learn how our secure smart contracts manage loan agreements
                    and repayments.
                  </p>
                  <Button variant="outline" className="mt-4">
                    Learn More
                  </Button>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <UsersIcon className="h-8 w-8 text-primary" />
                </CardHeader>
                <CardContent>
                  <h3 className="mb-2 text-lg font-bold">Community</h3>
                  <p className="text-muted-foreground">
                    Connect with other lenders and borrowers in our vibrant
                    community.
                  </p>
                  <Button variant="outline" className="mt-4">
                    Join Now
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-muted px-3 py-12 sm:py-16 md:py-20">
          <div className=" grid gap-8 md:grid-cols-2">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold sm:text-3xl md:text-4xl">
                Flexible Loan Terms
              </h2>
              <p className="text-muted-foreground">
                Lenders can set their own loan terms, including interest rates,
                collateral requirements, and repayment schedules. Borrowers can
                browse and select the best fit for their needs.
              </p>
              <div className="grid grid-cols-2 gap-4">
                <Card>
                  <CardHeader>
                    <CardTitle>Lender</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <span>Interest Rate</span>
                        <span className="font-medium">8.5%</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span>Loan Term</span>
                        <span className="font-medium">6 months</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span>Collateral</span>
                        <span className="font-medium">120%</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Borrower</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <span>Loan Amount</span>
                        <span className="font-medium">10,000 ALGO</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span>Collateral</span>
                        <span className="font-medium">12,000 ALGO</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span>Repayment</span>
                        <span className="font-medium">Monthly</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <Card>
                <CardHeader>
                  <HashIcon className="h-8 w-8 text-primary" />
                </CardHeader>
                <CardContent>
                  <h3 className="mb-2 text-lg font-bold">
                    Algorand Blockchain
                  </h3>
                  <p className="text-muted-foreground">
                    Our platform is built on the Algorand blockchain, ensuring
                    fast, secure, and low-cost transactions.
                  </p>
                  <Button variant="outline" className="mt-4">
                    Learn More
                  </Button>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <LockIcon className="h-8 w-8 text-primary" />
                </CardHeader>
                <CardContent>
                  <h3 className="mb-2 text-lg font-bold">Secure Lending</h3>
                  <p className="text-muted-foreground">
                    Our smart contracts and decentralized architecture provide
                    robust security for your assets.
                  </p>
                  <Button variant="outline" className="mt-4">
                    Learn More
                  </Button>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CoinsIcon className="h-8 w-8 text-primary" />
                </CardHeader>
                <CardContent>
                  <h3 className="mb-2 text-lg font-bold">Earn Yield</h3>
                  <p className="text-muted-foreground">
                    Lenders can earn attractive yields on their Algorand assets
                    by providing them as loans.
                  </p>
                  <Button variant="outline" className="mt-4">
                    Learn More
                  </Button>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CreditCardIcon className="h-8 w-8 text-primary" />
                </CardHeader>
                <CardContent>
                  <h3 className="mb-2 text-lg font-bold">Borrow Easily</h3>
                  <p className="text-muted-foreground">
                    Borrowers can access the funds they need quickly and
                    conveniently through our platform.
                  </p>
                  <Button variant="outline" className="mt-4">
                    Learn More
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className=" py-12 px-3 sm:py-16 md:py-20">
          <h2 className="mb-8 text-2xl font-bold sm:text-3xl md:text-4xl">
            Why Choose Algo Lend?
          </h2>
          <div className="grid gap-8 md:grid-cols-3">
            <Card>
              <CardHeader>
                <HashIcon className="h-8 w-8 text-primary" />
              </CardHeader>
              <CardContent>
                <h3 className="mb-2 text-lg font-bold">Algorand Powered</h3>
                <p className="text-muted-foreground">
                  Our platform is built on the Algorand blockchain, ensuring
                  fast, secure, and low-cost transactions.
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <ComponentIcon className="h-8 w-8 text-primary" />
              </CardHeader>
              <CardContent>
                <h3 className="mb-2 text-lg font-bold">Flexible Terms</h3>
                <p className="text-muted-foreground">
                  Lenders can set their own loan terms, and borrowers can find
                  the best fit for their needs.
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <LockIcon className="h-8 w-8 text-primary" />
              </CardHeader>
              <CardContent>
                <h3 className="mb-2 text-lg font-bold">Secure Lending</h3>
                <p className="text-muted-foreground">
                  Our smart contracts and decentralized architecture provide
                  robust security for your assets.
                </p>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
      <footer className="border-t bg-background">
        <div className=" flex items-center justify-between py-4 px-4 sm:px-6 md:px-8">
          <p className="text-sm text-muted-foreground">
            &copy; 2024 Algo Lend. All rights reserved.
          </p>
          <div className="flex items-center gap-4">
            <Link
              href="#"
              className="text-sm text-muted-foreground hover:underline"
              prefetch={false}
            >
              Terms of Service
            </Link>
            <Link
              href="#"
              className="text-sm text-muted-foreground hover:underline"
              prefetch={false}
            >
              Privacy Policy
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function CoinsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="8" r="6" />
      <path d="M18.09 10.37A6 6 0 1 1 10.34 18" />
      <path d="M7 6h1v4" />
      <path d="m16.71 13.88.7.71-2.82 2.82" />
    </svg>
  );
}

function ComponentIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5.5 8.5 9 12l-3.5 3.5L2 12l3.5-3.5Z" />
      <path d="m12 2 3.5 3.5L12 9 8.5 5.5 12 2Z" />
      <path d="M18.5 8.5 22 12l-3.5 3.5L15 12l3.5-3.5Z" />
      <path d="m12 15 3.5 3.5L12 22l-3.5-3.5L12 15Z" />
    </svg>
  );
}

function ContactIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 18a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <circle cx="12" cy="10" r="2" />
      <line x1="8" x2="8" y1="2" y2="4" />
      <line x1="16" x2="16" y1="2" y2="4" />
    </svg>
  );
}

function CreditCardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>
  );
}

function HashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="9" y2="9" />
      <line x1="4" x2="20" y1="15" y2="15" />
      <line x1="10" x2="8" y1="3" y2="21" />
      <line x1="16" x2="14" y1="3" y2="21" />
    </svg>
  );
}

function LockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  );
}

function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  );
}

function WalletIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1" />
      <path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4" />
    </svg>
  );
}
