/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CvRa78bQ9Pc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"

export function test() {
  return (
    (<div className="min-h-screen bg-black text-white">
      <header
        className="flex items-center justify-between p-4 border-b border-gray-700">
        <div className="flex items-center gap-4">
          <img src="/placeholder.svg" alt="Logo" className="h-8" />
          <nav className="flex gap-4">
            <Link href="#" className="text-lg font-semibold" prefetch={false}>
              Dashboard
            </Link>
            <Link href="#" className="text-lg font-semibold" prefetch={false}>
              Markets
            </Link>
            <Link href="#" className="text-lg font-semibold" prefetch={false}>
              Portfolio
            </Link>
          </nav>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="outline" className="text-white border-white">
            Connect Wallet
          </Button>
          <Button variant="ghost" className="text-white">
            <SettingsIcon className="w-6 h-6" />
          </Button>
          <Button variant="ghost" className="text-white">
            <UserIcon className="w-6 h-6" />
          </Button>
        </div>
      </header>
      <main className="p-4 space-y-8">
        <section className="bg-blue-600 p-4 rounded-md">
          <h2 className="text-lg font-semibold">Personal Stats</h2>
          <div className="flex justify-between mt-2">
            <div>
              Total Collateralized: <span className="font-bold">$1.04</span>
            </div>
            <div>
              Total Borrowed: <span className="font-bold">$0.00</span>
            </div>
            <div>
              Net APY: <span className="font-bold">3.92%</span>
            </div>
          </div>
        </section>
        <Button variant="outline" className="text-white border-white">
          View Your Stats
        </Button>
        <div className="flex gap-4">
          <Card className="w-full bg-gray-800 text-white">
            <CardHeader>
              <CardTitle>Your Loans</CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Loan Type</TableHead>
                    <TableHead>Collateral Balance</TableHead>
                    <TableHead>Borrow Balance</TableHead>
                    <TableHead>Liquidation Margin</TableHead>
                    <TableHead>Net APY</TableHead>
                    <TableHead>LTV</TableHead>
                    <TableHead />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>ik</TableCell>
                    <TableCell>GENERAL</TableCell>
                    <TableCell>$1.04</TableCell>
                    <TableCell>$0.00</TableCell>
                    <TableCell>
                      100% <Badge variant="success">Low Risk</Badge>
                    </TableCell>
                    <TableCell>3.92%</TableCell>
                    <TableCell>0%</TableCell>
                    <TableCell>
                      <Button variant="outline" className="text-white border-white">
                        Manage
                      </Button>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
            <CardFooter>
              <Button variant="outline" className="text-white border-white">
                + Create new Loan
              </Button>
            </CardFooter>
          </Card>
        </div>
        <div className="flex gap-4">
          <Card className="w-full bg-gray-800 text-white">
            <CardHeader>
              <CardTitle>Available to Collateralize</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-4 mb-4">
                <Input type="search" placeholder="Search" className="bg-gray-900 text-white" />
                <Select>
                  <SelectTrigger className="bg-gray-900 text-white">
                    <SelectValue placeholder="Filter by" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All</SelectItem>
                    <SelectItem value="available">Available</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Asset</TableHead>
                    <TableHead>Wallet Balance</TableHead>
                    <TableHead>APY</TableHead>
                    <TableHead />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>ALGO</TableCell>
                    <TableCell>9.54</TableCell>
                    <TableCell>3.92%</TableCell>
                    <TableCell>
                      <Button variant="outline" className="text-white border-white">
                        Collateralize
                      </Button>
                      <Button variant="outline" className="text-white border-white ml-2">
                        Swap and Collateralize
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>gALGO</TableCell>
                    <TableCell>0.00</TableCell>
                    <TableCell>0%</TableCell>
                    <TableCell>
                      <Button variant="outline" className="text-white border-white">
                        Collateralize
                      </Button>
                      <Button variant="outline" className="text-white border-white ml-2">
                        Swap and Collateralize
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>USD Coin</TableCell>
                    <TableCell>0.00</TableCell>
                    <TableCell>0.44%</TableCell>
                    <TableCell>
                      <Button variant="outline" className="text-white border-white">
                        Collateralize
                      </Button>
                      <Button variant="outline" className="text-white border-white ml-2">
                        Swap and Collateralize
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Bitcoin</TableCell>
                    <TableCell>0.00</TableCell>
                    <TableCell>0.84%</TableCell>
                    <TableCell>
                      <Button variant="outline" className="text-white border-white">
                        Collateralize
                      </Button>
                      <Button variant="outline" className="text-white border-white ml-2">
                        Swap and Collateralize
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Ethereum</TableCell>
                    <TableCell>0.00</TableCell>
                    <TableCell>0.06%</TableCell>
                    <TableCell>
                      <Button variant="outline" className="text-white border-white">
                        Collateralize
                      </Button>
                      <Button variant="outline" className="text-white border-white ml-2">
                        Swap and Collateralize
                      </Button>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
          <Card className="w-full bg-gray-800 text-white">
            <CardHeader>
              <CardTitle>Available to Borrow</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-4 mb-4">
                <Input type="search" placeholder="Search" className="bg-gray-900 text-white" />
                <Select>
                  <SelectTrigger className="bg-gray-900 text-white">
                    <SelectValue placeholder="Filter by" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All</SelectItem>
                    <SelectItem value="available">Available</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Asset</TableHead>
                    <TableHead>Available</TableHead>
                    <TableHead>Variable APY</TableHead>
                    <TableHead>Stable APY</TableHead>
                    <TableHead />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>ALGO</TableCell>
                    <TableCell>4,306.531805</TableCell>
                    <TableCell>6.96%</TableCell>
                    <TableCell>10.01%</TableCell>
                    <TableCell>
                      <Button variant="outline" className="text-white border-white">
                        Borrow
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>USD Coin</TableCell>
                    <TableCell>3,276.576049</TableCell>
                    <TableCell>2.51%</TableCell>
                    <TableCell>9.92%</TableCell>
                    <TableCell>
                      <Button variant="outline" className="text-white border-white">
                        Borrow
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Tether</TableCell>
                    <TableCell>686.86078</TableCell>
                    <TableCell>3.83%</TableCell>
                    <TableCell>8.13%</TableCell>
                    <TableCell>
                      <Button variant="outline" className="text-white border-white">
                        Borrow
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Bitcoin</TableCell>
                    <TableCell>0.04085512</TableCell>
                    <TableCell>3.44%</TableCell>
                    <TableCell>9.37%</TableCell>
                    <TableCell>
                      <Button variant="outline" className="text-white border-white">
                        Borrow
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Ethereum</TableCell>
                    <TableCell>0.58392603</TableCell>
                    <TableCell>0.81%</TableCell>
                    <TableCell>9%</TableCell>
                    <TableCell>
                      <Button variant="outline" className="text-white border-white">
                        Borrow
                      </Button>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>)
  );
}

function SettingsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}
