/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PjSrC2PB3wb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Switch } from "@/components/ui/switch"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function test() {
  return (
    (<div className="min-h-screen bg-black text-white">
      <header
        className="flex items-center justify-between p-4 border-b border-gray-700">
        <div className="flex items-center space-x-4">
          <img src="/placeholder.svg" alt="Logo" className="h-8" />
          <nav className="flex space-x-4">
            <a href="#" className="text-lg font-semibold">
              Dashboard
            </a>
            <a href="#" className="text-lg font-semibold">
              Markets
            </a>
            <a href="#" className="text-lg font-semibold">
              Portfolio
            </a>
          </nav>
        </div>
        <div className="flex items-center space-x-4">
          <button className="px-4 py-2 bg-blue-600 rounded-md">Connect Wallet</button>
          <button className="p-2 bg-gray-800 rounded-full">
            <SettingsIcon className="h-6 w-6" />
          </button>
          <button className="p-2 bg-gray-800 rounded-full">
            <UserIcon className="h-6 w-6" />
          </button>
        </div>
      </header>
      <main className="p-4 space-y-8">
        <section className="p-4 bg-blue-600 rounded-md">
          <div className="flex justify-between">
            <h2 className="text-lg font-semibold">Personal Stats</h2>
            <div className="flex items-center space-x-2">
              <span className="text-sm">View your stats</span>
              <Switch id="view-stats" />
            </div>
          </div>
          <div className="flex justify-between mt-4">
            <div className="flex space-x-4">
              <div className="text-sm">
                Total Collateralized: <span className="font-bold">$1.04</span>
              </div>
              <div className="text-sm">
                Total Borrowed: <span className="font-bold">$0.00</span>
              </div>
              <div className="text-sm">
                Net APY: <span className="font-bold">3.92%</span>
              </div>
            </div>
          </div>
        </section>
        <section className="space-y-4">
          <Tabs>
            <TabsList>
              <TabsTrigger> Your Loans </TabsTrigger>
              <TabsTrigger> Your Collaterals </TabsTrigger>
              <TabsTrigger> Your Borrows </TabsTrigger>
            </TabsList>
            <TabsContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Loan Type</TableHead>
                    <TableHead>Collateral Balance</TableHead>
                    <TableHead>Borrow Balance</TableHead>
                    <TableHead>Liquidation Margin</TableHead>
                    <TableHead>Net APY</TableHead>
                    <TableHead>LTV</TableHead>
                    <TableHead />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>ik</TableCell>
                    <TableCell>
                      <Button variant="outline">GENERAL</Button>
                    </TableCell>
                    <TableCell>$1.04</TableCell>
                    <TableCell>$0.00</TableCell>
                    <TableCell>
                      <Badge variant="secondary">100%</Badge>
                    </TableCell>
                    <TableCell>3.92%</TableCell>
                    <TableCell>0%</TableCell>
                    <TableCell>
                      <Button variant="outline">Manage</Button>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </TabsContent>
          </Tabs>
          <Button variant="outline" className="ml-auto">
            + Create new Loan
          </Button>
        </section>
        <section className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card className="bg-gray-800">
            <CardHeader>
              <CardTitle>Available to Collateralize</CardTitle>
              <div className="flex items-center space-x-2">
                <Input type="search" placeholder="Search" className="bg-gray-700" />
                <Select>
                  <SelectTrigger className="bg-gray-700">
                    <SelectValue placeholder="Filter by" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All</SelectItem>
                    <SelectItem value="assets">Assets</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Asset</TableHead>
                    <TableHead>Wallet Balance</TableHead>
                    <TableHead>APY</TableHead>
                    <TableHead />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>
                      <div className="flex items-center space-x-2">
                        <Avatar>
                          <AvatarImage src="/placeholder-user.jpg" alt="ALGO" />
                          <AvatarFallback>ALGO</AvatarFallback>
                        </Avatar>
                        <div>ALGO</div>
                      </div>
                    </TableCell>
                    <TableCell>9.54</TableCell>
                    <TableCell>3.92%</TableCell>
                    <TableCell>
                      <Button variant="secondary">Collateralize</Button>
                      <Button variant="secondary" className="ml-2">
                        Swap and Collateralize
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <div className="flex items-center space-x-2">
                        <Avatar>
                          <AvatarImage src="/placeholder-user.jpg" alt="gALGO" />
                          <AvatarFallback>gALGO</AvatarFallback>
                        </Avatar>
                        <div>gALGO</div>
                      </div>
                    </TableCell>
                    <TableCell>0.00</TableCell>
                    <TableCell>0%</TableCell>
                    <TableCell>
                      <Button variant="secondary">Collateralize</Button>
                      <Button variant="secondary" className="ml-2">
                        Swap and Collateralize
                      </Button>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
          <Card className="bg-gray-800">
            <CardHeader>
              <CardTitle>Available to Borrow</CardTitle>
              <div className="flex items-center space-x-2">
                <Input type="search" placeholder="Search" className="bg-gray-700" />
                <Select>
                  <SelectTrigger className="bg-gray-700">
                    <SelectValue placeholder="Filter by" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All</SelectItem>
                    <SelectItem value="assets">Assets</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Asset</TableHead>
                    <TableHead>Available</TableHead>
                    <TableHead>Variable APY</TableHead>
                    <TableHead>Stable APY</TableHead>
                    <TableHead />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>
                      <div className="flex items-center space-x-2">
                        <Avatar>
                          <AvatarImage src="/placeholder-user.jpg" alt="ALGO" />
                          <AvatarFallback>ALGO</AvatarFallback>
                        </Avatar>
                        <div>ALGO</div>
                      </div>
                    </TableCell>
                    <TableCell>4,306.531805</TableCell>
                    <TableCell>6.96%</TableCell>
                    <TableCell>10.01%</TableCell>
                    <TableCell>
                      <Button variant="secondary">Borrow</Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <div className="flex items-center space-x-2">
                        <Avatar>
                          <AvatarImage src="/placeholder-user.jpg" alt="USDC" />
                          <AvatarFallback>USDC</AvatarFallback>
                        </Avatar>
                        <div>USD Coin</div>
                      </div>
                    </TableCell>
                    <TableCell>3,276.576049</TableCell>
                    <TableCell>2.51%</TableCell>
                    <TableCell>9.92%</TableCell>
                    <TableCell>
                      <Button variant="secondary">Borrow</Button>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </section>
      </main>
    </div>)
  );
}

function SettingsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}
